### PR TITLE
[DOC] Updated feed graphite data command

### PR DESCRIPTION
**Pull request by hv7214**
# PR Summary
Added `-N` flag, which closes the network socket after EOF on the input. 

**Note**
This PR doesn't bring any breaking-change or bug-fix. It's just adds user comfortability.

### CODE REVIEW

**Comment by beevee** [comment]
> This PR doesn't bring any breaking-change

Or does it? In fact, `-N` breaks compatibility with MacOS and a number of other systems. `nc` flags are not very well standardized across platforms.

I'm disappointed with the amount of effort you put in this PR. At least you could consult with the original Graphite documentation (https://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-plaintext-protocol) that provides info on multiple possible flags.

**Comment by hv7214** [comment]
@beevee i'm really sorry for not diving deeper. I think it's better to use `Ctrl + C` to close the socket manually and write the same in README.

**Comment by beevee** [comment]
`Ctrl-C` won't work in automated scenarios when you want to write a script to send metrics.

**Comment by hv7214** [comment]
I guess that is possible in shell script.

**Comment by hv7214** [comment]
oh i see, `Ctrl + C` is a signal. Though we can send `Ctrl + C` signal in bash script.

**Comment by hv7214** [comment]
@litleleprikon closing this PR

**Pull request closed without merging**
