### PR TITLE
net/http library's consts for representing http codes

### PR DESCRIPTION
**Pull request by maksgalimz**
# Http codes

Using http package consts instead bare numbers for http codes

### CODE REVIEW

**Comment by kissken** [comment]
will other pkg be in another PR?

**Comment by maksgalimz** [comment]
what other pkg?

**Comment by kissken** [comment]
example:
https://github.com/moira-alert/moira/blob/master/metric_source/remote/request.go#L45
https://github.com/moira-alert/moira/blob/master/senders/victorops/api/alert.go#L60

**Review by kissken — APPROVED** [review]
uhuuuu!

**Pull request merged**
